openapi: 3.1.0
info:
  title: 서울 대중교통 경로 안내 API
  description: 서울 지하철 및 버스를 이용한 경로 안내와 접근성 정보를 제공하는 API
  version: 1.0.0
servers:
  - url: https://easyway-gpts.vercel.app
    description: Vercel 배포 서버
paths:
  /get-transit-directions:
    get:
      operationId: getTransitDirections
      summary: 대중교통 경로 안내 (시뮬레이션)
      description: 출발지와 목적지 좌표를 기반으로 대중교통 경로와 접근성 정보를 제공합니다. 이 API는 실제 대중교통 데이터가 아닌 시뮬레이션된 경로를 제공합니다.
      parameters:
        - name: start
          in: query
          required: true
          description: 출발지 좌표 (경도,위도 형식)
          schema:
            type: string
        - name: goal
          in: query
          required: true
          description: 목적지 좌표 (경도,위도 형식)
          schema:
            type: string
        - name: includeAccessibility
          in: query
          required: false
          description: 접근성 정보 포함 여부 (true/false)
          schema:
            type: string
            enum: [true, false]
            default: true
      responses:
        '200':
          description: 성공적인 응답
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: 응답 코드
                  message:
                    type: string
                    description: 응답 메시지
                  route:
                    type: object
                    description: 경로 정보
                  accessibility:
                    type: object
                    description: 접근성 정보
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 오류
  
  /get-subway-route:
    get:
      operationId: getSubwayRoute
      summary: 지하철 경로 안내
      description: 출발지와 목적지 좌표를 기반으로 실제 지하철 노선도를 활용한 경로와 접근성 정보를 제공합니다.
      parameters:
        - name: start
          in: query
          required: true
          description: 출발지 좌표 (경도,위도 형식)
          schema:
            type: string
        - name: goal
          in: query
          required: true
          description: 목적지 좌표 (경도,위도 형식)
          schema:
            type: string
        - name: includeAccessibility
          in: query
          required: false
          description: 접근성 정보 포함 여부 (true/false)
          schema:
            type: string
            enum: [true, false]
            default: true
      responses:
        '200':
          description: 성공적인 응답
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: 응답 코드
                  message:
                    type: string
                    description: 응답 메시지
                  route:
                    type: object
                    description: 경로 정보
                  accessibility:
                    type: object
                    description: 접근성 정보
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 오류
  
  /get-bus-route:
    get:
      operationId: getBusRoute
      summary: 버스 경로 안내
      description: 출발지와 목적지 좌표를 기반으로 버스 경로와 접근성 정보를 제공합니다.
      parameters:
        - name: start
          in: query
          required: true
          description: 출발지 좌표 (경도,위도 형식)
          schema:
            type: string
        - name: goal
          in: query
          required: true
          description: 목적지 좌표 (경도,위도 형식)
          schema:
            type: string
        - name: includeAccessibility
          in: query
          required: false
          description: 접근성 정보 포함 여부 (true/false)
          schema:
            type: string
            enum: [true, false]
            default: true
      responses:
        '200':
          description: 성공적인 응답
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: 응답 코드
                  message:
                    type: string
                    description: 응답 메시지
                  route:
                    type: object
                    description: 경로 정보
                  accessibility:
                    type: object
                    description: 접근성 정보
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 오류
  
  /get-combined-route:
    get:
      operationId: getCombinedRoute
      summary: 복합 대중교통 경로 안내
      description: 출발지와 목적지 좌표를 기반으로 지하철과 버스를 모두 활용한 복합 경로와 접근성 정보를 제공합니다.
      parameters:
        - name: start
          in: query
          required: true
          description: 출발지 좌표 (경도,위도 형식)
          schema:
            type: string
        - name: goal
          in: query
          required: true
          description: 목적지 좌표 (경도,위도 형식)
          schema:
            type: string
        - name: includeAccessibility
          in: query
          required: false
          description: 접근성 정보 포함 여부 (true/false)
          schema:
            type: string
            enum: [true, false]
            default: true
      responses:
        '200':
          description: 성공적인 응답
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: 응답 코드
                  message:
                    type: string
                    description: 응답 메시지
                  route:
                    type: object
                    description: 경로 정보
                    properties:
                      summary:
                        type: object
                        description: 경로 요약 정보
                      legs:
                        type: array
                        description: 경로 구간 정보
                      realtime:
                        type: object
                        description: 실시간 정보
                  accessibility:
                    type: object
                    description: 접근성 정보
                    properties:
                      facilities:
                        type: array
                        description: 접근성 시설 목록
                      count:
                        type: integer
                        description: 접근성 시설 수
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 오류 